stages:
 - run_job

run_job:
  stage: run_job
  tags:
    - linux
  script:
    - # ./pipeline.sh
    - sudo mkdir -p ~/.ssh
    - sudo echo $THE_WAY
    - sudo echo $THE_WAY > ~/.ssh/id_rsa 
    - sudo chmod 600 ~/.ssh/id_rsa
    - sudo cat ~/.ssh/id_rsa
    - sudo ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa -T ian@192.168.0.16 'uptime'
