stages:
 - run_job

run_job:
  stage: run_job
  tags:
    - linux
  script:
    - sudo mkdir -p ~/.ssh
    - sudo echo $THE_WAY |base64 --decode > ~/.ssh/the_way
    - sudo chmod 600 ~/.ssh/the_way
    - sudo scp -o StrictHostKeyChecking=no -i ~/.ssh/the_way -T Vagrant_Kubernetes_Setup.sh ian@192.168.0.16:Documents/src/test/Vagrant_Kubernetes_Setup.sh
