all:
  hosts:
    node1:
      ansible_host: 192.168.200.201
      ip: 192.168.200.201
      access_ip: 192.168.200.201
    node2:
      ansible_host: 192.168.200.202
      ip: 192.168.200.202
      access_ip: 192.168.200.202
    node3:
      ansible_host: 192.168.200.203
      ip: 192.168.200.203
      access_ip: 192.168.200.203
    node4:
      ansible_host: 192.168.200.204
      ip: 192.168.200.204
      access_ip: 192.168.200.204
    node5:
      ansible_host: 192.168.200.205
      ip: 192.168.200.205
      access_ip: 192.168.200.205
  children:
    kube_control_plane:
      hosts:
        node1:
        node2:
        node3:
    kube_node:
      hosts:
        node4:
        node5:
    etcd:
      hosts:
        node1:
        node2:
        node3:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
