.ssh_setup:
  before_script:
    - sudo mkdir -p ~/.ssh
    - echo "$THE_WAY" | base64 --decode | sudo tee ~/.ssh/the_way > /dev/null
    - sudo chmod 600 ~/.ssh/the_way

stages:
 - destroy_job
 - up_only_job
 - skip_up_job

destroy_job:
  extends: .ssh_setup
  image: docker.ellisbs.co.uk:5190/ubuntu:24.04
  stage: destroy_job
  tags:
    - linux
  script:
    - sudo ssh -o StrictHostKeyChecking=no -i ~/.ssh/the_way -T $TEST_TARGET "if [ -f Documents/src/test/Vagrantfile ]; then echo \"Vagrantfile found. Proceeding with destruction...\"; cd Documents/src/test && vagrant destroy -f; else echo \"No Vagrantfile found. Exiting gracefully.\"; exit 0; fi"

up_only_job:
  extends: .ssh_setup
  image: docker.ellisbs.co.uk:5190/ubuntu:24.04
  stage: up_only_job
  tags:
    - linux
  timeout: 3h
  retry:
    max: 2
    when:
      - script_failure
      - api_failure
  script:
    - sudo scp -o StrictHostKeyChecking=no -i ~/.ssh/the_way -T Make_Kubernetes.sh $TEST_TARGET:Documents/src/test/Make_Kubernetes.sh
    - sudo scp -o StrictHostKeyChecking=no -i ~/.ssh/the_way -T config.json $TEST_TARGET:Documents/src/test/config.json
    - sudo scp -o StrictHostKeyChecking=no -i ~/.ssh/the_way -T Vagrantfile.template $TEST_TARGET:Documents/src/test/Vagrantfile.template
    - sudo ssh -o StrictHostKeyChecking=no -i ~/.ssh/the_way -T $TEST_TARGET "cd Documents/src/test && ./Make_Kubernetes.sh --location vagrant UP_ONLY"

skip_up_job:
  extends: .ssh_setup
  image: docker.ellisbs.co.uk:5190/ubuntu:24.04
  stage: skip_up_job
  tags:
    - linux
  timeout: 3h
  script:
    - sudo scp -o StrictHostKeyChecking=no -i ~/.ssh/the_way -T hosts.template $TEST_TARGET:Documents/src/test/hosts.template
    - sudo scp -o StrictHostKeyChecking=no -i ~/.ssh/the_way -T addons.yml $TEST_TARGET:Documents/src/test/addons.yml
    - sudo scp -o StrictHostKeyChecking=no -i ~/.ssh/the_way -T build_inventory.template $TEST_TARGET:Documents/src/test/build_inventory.template
    - sudo scp -o StrictHostKeyChecking=no -i ~/.ssh/the_way -T systemd/service-monitor.service $TEST_TARGET:Documents/src/test/service-monitor.service
    - sudo scp -o StrictHostKeyChecking=no -i ~/.ssh/the_way -T systemd/service-monitor.sh $TEST_TARGET:Documents/src/test/service-monitor.sh
    - sudo scp -o StrictHostKeyChecking=no -i ~/.ssh/the_way -T ansible.cfg $TEST_TARGET:Documents/src/test/ansible.cfg
    - echo "sudo ssh -o StrictHostKeyChecking=no -i ~/.ssh/the_way -T $TEST_TARGET \"export OPENAI_API_KEY=$OPENAI_API_KEY && cd Documents/src/test && ./Make_Kubernetes.sh --location vagrant SKIP_UP\"" > /tmp/dynamics_action.sh
    - sh /tmp/dynamics_action.sh
