apiVersion: batch/v1
kind: CronJob
metadata:
  name: velero-backup
  namespace: default
spec:
  schedule: "0 2 * * *" # Run at 2:00 AM daily
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: velero-backup
            image: velero/velero:v1.12.0
            args:
            - backup
            - create
            - "$(BACKUP_NAME)"
            - --include-cluster-resources=true
            env:
            - name: BACKUP_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.creationTimestamp
          restartPolicy: OnFailure
          serviceAccountName: velero
